In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
column_names = ["item_id", "movie_title", "release date", "video release date", "IMDb URL", "unknown", "Action", "Adventure", "Animation", "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"]
item = pd.read_csv("ml-100k/u.item", sep='|', names = column_names, encoding='latin-1')
item

item_id                                movie_title release date  \
0           1                           Toy Story (1995)  01-Jan-1995   
1           2                           GoldenEye (1995)  01-Jan-1995   
2           3                          Four Rooms (1995)  01-Jan-1995   
3           4                          Get Shorty (1995)  01-Jan-1995   
4           5                             Copycat (1995)  01-Jan-1995   
...       ...                                        ...          ...   
1677     1678                          Mat' i syn (1997)  06-Feb-1998   
1678     1679                           B. Monkey (1998)  06-Feb-1998   
1679     1680                       Sliding Doors (1998)  01-Jan-1998   
1680     1681                        You So Crazy (1994)  01-Jan-1994   
1681     1682  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      video release date                                           IMDb URL  \
0                    NaN  http://us.imdb.com/M/title-exact?Toy%20Story%2...   
1                    NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...   
2                    NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...   
3                    NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...   
4                    NaN  http://us.imdb.com/M/title-exact?Copycat%20(1995)   
...                  ...                                                ...   
1677                 NaN  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...   
1678                 NaN  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...   
1679                 NaN      http://us.imdb.com/Title?Sliding+Doors+(1998)   
1680                 NaN  http://us.imdb.com/M/title-exact?You%20So%20Cr...   
1681                 NaN  http://us.imdb.com/M/title-exact?Schrei%20aus%...   

      unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
0           0       0          0          1           1  ...        0   
1           0       1          1          0           0  ...        0   
2           0       0          0          0           0  ...        0   
3           0       1          0          0           0  ...        0   
4           0       0          0          0           0  ...        0   
...       ...     ...        ...        ...         ...  ...      ...   
1677        0       0          0          0           0  ...        0   
1678        0       0          0          0           0  ...        0   
1679        0       0          0          0           0  ...        0   
1680        0       0          0          0           0  ...        0   
1681        0       0          0          0           0  ...        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1677          0       0        0        0        0       0         0    0   
1678          0       0        0        0        1       0         1    0   
1679          0       0        0        0        1       0         0    0   
1680          0       0        0        0        0       0         0    0   
1681          0       0        0        0        0       0         0    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1677        0  
1678        0  
1679        0  
1680        0  
1681        0  

[1682 rows x 24 columns]

In [3]:
print(item.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1682 entries, 0 to 1681
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   item_id             1682 non-null   int64  
 1   movie_title         1682 non-null   object 
 2   release date        1681 non-null   object 
 3   video release date  0 non-null      float64
 4   IMDb URL            1679 non-null   object 
 5   unknown             1682 non-null   int64  
 6   Action              1682 non-null   int64  
 7   Adventure           1682 non-null   int64  
 8   Animation           1682 non-null   int64  
 9   Children's          1682 non-null   int64  
 10  Comedy              1682 non-null   int64  
 11  Crime               1682 non-null   int64  
 12  Documentary         1682 non-null   int64  
 13  Drama               1682 non-null   int64  
 14  Fantasy             1682 non-null   int64  
 15  Film-Noir           1682 non-null   int64  
 16  Horror

In [4]:
index_movie_dict = {}
for i in range(len(item)):
    index_movie_dict[i] = item.loc[i]['movie_title']

In [5]:
index_movie_dict

{0: 'Toy Story (1995)',
 1: 'GoldenEye (1995)',
 2: 'Four Rooms (1995)',
 3: 'Get Shorty (1995)',
 4: 'Copycat (1995)',
 5: 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
 6: 'Twelve Monkeys (1995)',
 7: 'Babe (1995)',
 8: 'Dead Man Walking (1995)',
 9: 'Richard III (1995)',
 10: 'Seven (Se7en) (1995)',
 11: 'Usual Suspects, The (1995)',
 12: 'Mighty Aphrodite (1995)',
 13: 'Postino, Il (1994)',
 14: "Mr. Holland's Opus (1995)",
 15: 'French Twist (Gazon maudit) (1995)',
 16: 'From Dusk Till Dawn (1996)',
 17: 'White Balloon, The (1995)',
 18: "Antonia's Line (1995)",
 19: 'Angels and Insects (1995)',
 20: 'Muppet Treasure Island (1996)',
 21: 'Braveheart (1995)',
 22: 'Taxi Driver (1976)',
 23: 'Rumble in the Bronx (1995)',
 24: 'Birdcage, The (1996)',
 25: 'Brothers McMullen, The (1995)',
 26: 'Bad Boys (1995)',
 27: 'Apollo 13 (1995)',
 28: 'Batman Forever (1995)',
 29: 'Belle de jour (1967)',
 30: 'Crimson Tide (1995)',
 31: 'Crumb (1994)',
 32: 'Desperado (1995)',
 33: 'D

In [6]:
movie_index_dict = {}
for i in range(len(item)):
    movie_index_dict[item.loc[i]['movie_title']] = i

In [7]:
movie_index_dict

{'Toy Story (1995)': 0,
 'GoldenEye (1995)': 1,
 'Four Rooms (1995)': 2,
 'Get Shorty (1995)': 3,
 'Copycat (1995)': 4,
 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)': 5,
 'Twelve Monkeys (1995)': 6,
 'Babe (1995)': 7,
 'Dead Man Walking (1995)': 8,
 'Richard III (1995)': 9,
 'Seven (Se7en) (1995)': 10,
 'Usual Suspects, The (1995)': 11,
 'Mighty Aphrodite (1995)': 12,
 'Postino, Il (1994)': 13,
 "Mr. Holland's Opus (1995)": 14,
 'French Twist (Gazon maudit) (1995)': 15,
 'From Dusk Till Dawn (1996)': 16,
 'White Balloon, The (1995)': 17,
 "Antonia's Line (1995)": 18,
 'Angels and Insects (1995)': 19,
 'Muppet Treasure Island (1996)': 20,
 'Braveheart (1995)': 21,
 'Taxi Driver (1976)': 22,
 'Rumble in the Bronx (1995)': 23,
 'Birdcage, The (1996)': 24,
 'Brothers McMullen, The (1995)': 25,
 'Bad Boys (1995)': 26,
 'Apollo 13 (1995)': 27,
 'Batman Forever (1995)': 28,
 'Belle de jour (1967)': 29,
 'Crimson Tide (1995)': 30,
 'Crumb (1994)': 31,
 'Desperado (1995)': 32,
 'Doom 

In [8]:
item.drop(["item_id", "movie_title", "release date", "video release date", "IMDb URL"], axis = 1, inplace = True)
item

unknown  Action  Adventure  Animation  Children's  Comedy  Crime  \
0           0       0          0          1           1       1      0   
1           0       1          1          0           0       0      0   
2           0       0          0          0           0       0      0   
3           0       1          0          0           0       1      0   
4           0       0          0          0           0       0      1   
...       ...     ...        ...        ...         ...     ...    ...   
1677        0       0          0          0           0       0      0   
1678        0       0          0          0           0       0      0   
1679        0       0          0          0           0       0      0   
1680        0       0          0          0           0       1      0   
1681        0       0          0          0           0       0      0   

      Documentary  Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  \
0               0      0        0          0       0        0        0   
1               0      0        0          0       0        0        0   
2               0      0        0          0       0        0        0   
3               0      1        0          0       0        0        0   
4               0      1        0          0       0        0        0   
...           ...    ...      ...        ...     ...      ...      ...   
1677            0      1        0          0       0        0        0   
1678            0      0        0          0       0        0        0   
1679            0      1        0          0       0        0        0   
1680            0      0        0          0       0        0        0   
1681            0      1        0          0       0        0        0   

      Romance  Sci-Fi  Thriller  War  Western  
0           0       0         0    0        0  
1           0       0         1    0        0  
2           0       0         1    0        0  
3           0       0         0    0        0  
4           0       0         1    0        0  
...       ...     ...       ...  ...      ...  
1677        0       0         0    0        0  
1678        1       0         1    0        0  
1679        1       0         0    0        0  
1680        0       0         0    0        0  
1681        0       0         0    0        0  

[1682 rows x 19 columns]

In [10]:
item.columns

Index(['unknown', 'Action', 'Adventure', 'Animation', 'Children's', 'Comedy',
       'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror',
       'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'],
      dtype='object')

In [11]:
genres = item.to_numpy()

In [12]:
genres

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
from sklearn.metrics.pairwise import sigmoid_kernel
genres_similarity_matrix = sigmoid_kernel(genres, genres)
print(genres_similarity_matrix)

[[0.8203526  0.76159416 0.76159416 ... 0.76159416 0.78282736 0.76159416]
 [0.76159416 0.8203526  0.78282736 ... 0.76159416 0.76159416 0.76159416]
 [0.76159416 0.78282736 0.78282736 ... 0.76159416 0.76159416 0.76159416]
 ...
 [0.76159416 0.76159416 0.76159416 ... 0.80238161 0.76159416 0.78282736]
 [0.78282736 0.76159416 0.76159416 ... 0.76159416 0.78282736 0.76159416]
 [0.76159416 0.76159416 0.76159416 ... 0.78282736 0.76159416 0.78282736]]


In [15]:
genres_similarity_matrix.shape

(1682, 1682)

In [14]:
print(genres_similarity_matrix[0])

[0.8203526  0.76159416 0.76159416 ... 0.76159416 0.78282736 0.76159416]


In [15]:
index_movie_dict.values()

dict_values(['Toy Story (1995)', 'GoldenEye (1995)', 'Four Rooms (1995)', 'Get Shorty (1995)', 'Copycat (1995)', 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)', 'Twelve Monkeys (1995)', 'Babe (1995)', 'Dead Man Walking (1995)', 'Richard III (1995)', 'Seven (Se7en) (1995)', 'Usual Suspects, The (1995)', 'Mighty Aphrodite (1995)', 'Postino, Il (1994)', "Mr. Holland's Opus (1995)", 'French Twist (Gazon maudit) (1995)', 'From Dusk Till Dawn (1996)', 'White Balloon, The (1995)', "Antonia's Line (1995)", 'Angels and Insects (1995)', 'Muppet Treasure Island (1996)', 'Braveheart (1995)', 'Taxi Driver (1976)', 'Rumble in the Bronx (1995)', 'Birdcage, The (1996)', 'Brothers McMullen, The (1995)', 'Bad Boys (1995)', 'Apollo 13 (1995)', 'Batman Forever (1995)', 'Belle de jour (1967)', 'Crimson Tide (1995)', 'Crumb (1994)', 'Desperado (1995)', 'Doom Generation, The (1995)', 'Free Willy 2: The Adventure Home (1995)', 'Mad Love (1995)', 'Nadja (1994)', 'Net, The (1995)', 'Strange Days (1995)'

In [16]:
def getRecommendations(movie_name):
    idx = movie_index_dict[movie_name]
    similarity_list = genres_similarity_matrix[idx]
    lst = []
    for i in range(len(similarity_list)):
        lst.append((similarity_list[i],i))
    return sorted(lst, reverse = True)

# Get recommendations corresponding to a movie

In [17]:
recommendations_list = getRecommendations('Star Wars (1977)')
for element in recommendations_list:
    print(index_movie_dict[element[1]])

Return of the Jedi (1983)
Empire Strikes Back, The (1980)
Star Wars (1977)
African Queen, The (1951)
Starship Troopers (1997)
Cutthroat Island (1995)
Time Tracers (1995)
Escape from L.A. (1996)
Congo (1995)
Jumanji (1995)
First Knight (1995)
Escape from New York (1981)
Crying Game, The (1992)
Kid in King Arthur's Court, A (1995)
Star Trek V: The Final Frontier (1989)
Star Trek: The Motion Picture (1979)
Transformers: The Movie, The (1986)
Super Mario Bros. (1993)
True Lies (1994)
Star Trek: Generations (1994)
Judge Dredd (1995)
Spawn (1997)
Men in Black (1997)
Lost World: Jurassic Park, The (1997)
Last of the Mohicans, The (1992)
Mars Attacks! (1996)
Star Trek IV: The Voyage Home (1986)
Star Trek III: The Search for Spock (1984)
Star Trek: The Wrath of Khan (1982)
Star Trek VI: The Undiscovered Country (1991)
Star Trek: First Contact (1996)
Army of Darkness (1993)
Aliens (1986)
Princess Bride, The (1987)
Abyss, The (1989)
Independence Day (ID4) (1996)
Operation Dumbo Drop (1995)
Heavy 

# Resolving the issue of having the recently watched movie in the recommendation list

In [25]:
recommendations_list = getRecommendations('Star Wars (1977)')
final_recommendation_list = []
for element in recommendations_list:
    final_recommendation_list.append(index_movie_dict[element[1]])
final_recommendation_list.remove('Star Wars (1977)')
final_recommendation_list[:10]

['Return of the Jedi (1983)',
 'Empire Strikes Back, The (1980)',
 'African Queen, The (1951)',
 'Starship Troopers (1997)',
 'Cutthroat Island (1995)',
 'Time Tracers (1995)',
 'Escape from L.A. (1996)',
 'Congo (1995)',
 'Jumanji (1995)',
 'First Knight (1995)']

In [32]:
def recommend_movies(movie_title, number_of_recommendations):
    recommendations_list = getRecommendations(movie_title)
    final_recommendation_list = []
    for element in recommendations_list:
        final_recommendation_list.append(index_movie_dict[element[1]])
    final_recommendation_list.remove(movie_title)
    for movie in final_recommendation_list[:number_of_recommendations]:
        print(movie)

In [38]:
recommend_movies('Star Wars (1977)', 10)

Return of the Jedi (1983)
Empire Strikes Back, The (1980)
African Queen, The (1951)
Starship Troopers (1997)
Cutthroat Island (1995)
Time Tracers (1995)
Escape from L.A. (1996)
Congo (1995)
Jumanji (1995)
First Knight (1995)


In [39]:
recommend_movies('Lion King, The (1994)', 10)

Pete's Dragon (1977)
Hercules (1997)
Cats Don't Dance (1997)
Three Caballeros, The (1945)
Hunchback of Notre Dame, The (1996)
Beauty and the Beast (1991)
Pocahontas (1995)
Anastasia (1997)
Dumbo (1941)
James and the Giant Peach (1996)


In [40]:
recommend_movies('Jurassic Park (1993)', 20)

Time Tracers (1995)
Escape from L.A. (1996)
Congo (1995)
Jumanji (1995)
Escape from New York (1981)
Star Trek V: The Final Frontier (1989)
Star Trek: The Motion Picture (1979)
Super Mario Bros. (1993)
Star Trek: Generations (1994)
Judge Dredd (1995)
Spawn (1997)
Starship Troopers (1997)
Men in Black (1997)
Lost World: Jurassic Park, The (1997)
Star Trek IV: The Voyage Home (1986)
Star Trek III: The Search for Spock (1984)
Star Trek: The Wrath of Khan (1982)
Star Trek VI: The Undiscovered Country (1991)
Star Trek: First Contact (1996)
Army of Darkness (1993)


In [6]:
item

item_id                                movie_title release date  \
0           1                           Toy Story (1995)  01-Jan-1995   
1           2                           GoldenEye (1995)  01-Jan-1995   
2           3                          Four Rooms (1995)  01-Jan-1995   
3           4                          Get Shorty (1995)  01-Jan-1995   
4           5                             Copycat (1995)  01-Jan-1995   
...       ...                                        ...          ...   
1677     1678                          Mat' i syn (1997)  06-Feb-1998   
1678     1679                           B. Monkey (1998)  06-Feb-1998   
1679     1680                       Sliding Doors (1998)  01-Jan-1998   
1680     1681                        You So Crazy (1994)  01-Jan-1994   
1681     1682  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      video release date                                           IMDb URL  \
0                    NaN  http://us.imdb.com/M/title-exact?Toy%20Story%2...   
1                    NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...   
2                    NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...   
3                    NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...   
4                    NaN  http://us.imdb.com/M/title-exact?Copycat%20(1995)   
...                  ...                                                ...   
1677                 NaN  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...   
1678                 NaN  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...   
1679                 NaN      http://us.imdb.com/Title?Sliding+Doors+(1998)   
1680                 NaN  http://us.imdb.com/M/title-exact?You%20So%20Cr...   
1681                 NaN  http://us.imdb.com/M/title-exact?Schrei%20aus%...   

      unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
0           0       0          0          1           1  ...        0   
1           0       1          1          0           0  ...        0   
2           0       0          0          0           0  ...        0   
3           0       1          0          0           0  ...        0   
4           0       0          0          0           0  ...        0   
...       ...     ...        ...        ...         ...  ...      ...   
1677        0       0          0          0           0  ...        0   
1678        0       0          0          0           0  ...        0   
1679        0       0          0          0           0  ...        0   
1680        0       0          0          0           0  ...        0   
1681        0       0          0          0           0  ...        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1677          0       0        0        0        0       0         0    0   
1678          0       0        0        0        1       0         1    0   
1679          0       0        0        0        1       0         0    0   
1680          0       0        0        0        0       0         0    0   
1681          0       0        0        0        0       0         0    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1677        0  
1678        0  
1679        0  
1680        0  
1681        0  

[1682 rows x 24 columns]

In [10]:
posters = pd.read_csv('movie_poster.csv', names = ['item_id', 'poster_link'])
df = posters.merge(item, on="item_id")
df = df.drop(columns=["unknown", "Action", "Adventure", "Animation", "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"])
df

item_id                                        poster_link  \
0           1  https://images-na.ssl-images-amazon.com/images...   
1           2  https://images-na.ssl-images-amazon.com/images...   
2           3  https://images-na.ssl-images-amazon.com/images...   
3           4  https://images-na.ssl-images-amazon.com/images...   
4           5  https://images-na.ssl-images-amazon.com/images...   
...       ...                                                ...   
1587     1678  https://images-na.ssl-images-amazon.com/images...   
1588     1679  https://images-na.ssl-images-amazon.com/images...   
1589     1680  https://images-na.ssl-images-amazon.com/images...   
1590     1681  https://images-na.ssl-images-amazon.com/images...   
1591     1682  https://images-na.ssl-images-amazon.com/images...   

                                    movie_title release date  \
0                              Toy Story (1995)  01-Jan-1995   
1                              GoldenEye (1995)  01-Jan-1995   
2                             Four Rooms (1995)  01-Jan-1995   
3                             Get Shorty (1995)  01-Jan-1995   
4                                Copycat (1995)  01-Jan-1995   
...                                         ...          ...   
1587                          Mat' i syn (1997)  06-Feb-1998   
1588                           B. Monkey (1998)  06-Feb-1998   
1589                       Sliding Doors (1998)  01-Jan-1998   
1590                        You So Crazy (1994)  01-Jan-1994   
1591  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      video release date                                           IMDb URL  
0                    NaN  http://us.imdb.com/M/title-exact?Toy%20Story%2...  
1                    NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...  
2                    NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...  
3                    NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...  
4                    NaN  http://us.imdb.com/M/title-exact?Copycat%20(1995)  
...                  ...                                                ...  
1587                 NaN  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...  
1588                 NaN  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...  
1589                 NaN      http://us.imdb.com/Title?Sliding+Doors+(1998)  
1590                 NaN  http://us.imdb.com/M/title-exact?You%20So%20Cr...  
1591                 NaN  http://us.imdb.com/M/title-exact?Schrei%20aus%...  

[1592 rows x 6 columns]

In [13]:
movies_list = df['movie_title']
poster_link = df['poster_link']
print(len(movies_list))
print(len(poster_link))

1592
1592


In [15]:
movies_list = df['movie_title']
poster_link = df['poster_link']
movie_poster_dict = {}
for i in range(len(df)):
    movie_poster_dict[movies_list[i]] = poster_link[i]
movie_poster_dict

{'Toy Story (1995)': 'https://images-na.ssl-images-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@..jpg',
 'GoldenEye (1995)': 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzk2OTg4MTk1NF5BMl5BanBnXkFtZTcwNjExNTgzNA@@..jpg',
 'Four Rooms (1995)': 'https://images-na.ssl-images-amazon.com/images/M/MV5BNDc3Y2YwMjUtYzlkMi00MTljLTg1ZGMtYzUwODljZTI1OTZjXkEyXkFqcGdeQXVyMTQxNzMzNDI@..jpg',
 'Get Shorty (1995)': 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjAwODYzNDY4Ml5BMl5BanBnXkFtZTcwODkwNTgzNA@@..jpg',
 'Copycat (1995)': 'https://images-na.ssl-images-amazon.com/images/M/MV5BYWUwNDk2ZDYtNmFkMi00NjE5LWE1M2ItYTRkNTFjZDU3ZDU4L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTYxNjkxOQ@@..jpg',
 'Twelve Monkeys (1995)': 'https://images-na.ssl-images-amazon.com/images/M/MV5BN2Y2OWU4MWMtNmIyMy00YzMyLWI0Y2ItMTcyZDc3MTdmZDU4XkEyXkFqcGdeQXVyMTQxNzMzNDI@..jpg',
 'Babe (1995)': 'https://images-na.ssl-images-amazon.com/images/M/MV5BYjg4ZjUzMzMtYzlmYi0

In [19]:
column_names = ["item_id", "movie_title", "release date", "video release date", "IMDb URL", "unknown", "Action", "Adventure", "Animation", "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"]
item = pd.read_csv("ml-100k/u.item", sep='|', names = column_names, encoding='latin-1')
movies_list = item['movie_title']
release_date = item['release date']
movie_release_date_dict = {}
for i in range(len(item)):
    movie_release_date_dict[movies_list[i]] = release_date[i]
movie_release_date_dict

In [22]:
movie_release_date_dict = {}
for i in range(len(item)):
    movie_release_date_dict[movies_list[i]] = release_date[i]
movie_release_date_dict

{'Toy Story (1995)': '01-Jan-1995',
 'GoldenEye (1995)': '01-Jan-1995',
 'Four Rooms (1995)': '01-Jan-1995',
 'Get Shorty (1995)': '01-Jan-1995',
 'Copycat (1995)': '01-Jan-1995',
 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)': '01-Jan-1995',
 'Twelve Monkeys (1995)': '01-Jan-1995',
 'Babe (1995)': '01-Jan-1995',
 'Dead Man Walking (1995)': '01-Jan-1995',
 'Richard III (1995)': '22-Jan-1996',
 'Seven (Se7en) (1995)': '01-Jan-1995',
 'Usual Suspects, The (1995)': '14-Aug-1995',
 'Mighty Aphrodite (1995)': '30-Oct-1995',
 'Postino, Il (1994)': '01-Jan-1994',
 "Mr. Holland's Opus (1995)": '29-Jan-1996',
 'French Twist (Gazon maudit) (1995)': '01-Jan-1995',
 'From Dusk Till Dawn (1996)': '05-Feb-1996',
 'White Balloon, The (1995)': '01-Jan-1995',
 "Antonia's Line (1995)": '01-Jan-1995',
 'Angels and Insects (1995)': '01-Jan-1995',
 'Muppet Treasure Island (1996)': '16-Feb-1996',
 'Braveheart (1995)': '16-Feb-1996',
 'Taxi Driver (1976)': '16-Feb-1996',
 'Rumble in the Bronx (1995)